# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fingerrails}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra", "Eloy Duran"]
  s.date = %q{2009-10-29}
  s.default_executable = %q{fingerrails}
  s.description = %q{A self contained version of the Fingertips Rails template}
  s.email = %q{eloy@fngtps.com}
  s.executables = ["fingerrails"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/fingerrails",
     "fingerrails.gemspec",
     "fingertips.rb",
     "templates/.kick",
     "templates/Rakefile",
     "templates/app/controllers/application_controller.rb",
     "templates/app/controllers/members_controller.rb",
     "templates/app/controllers/passwords_controller.rb",
     "templates/app/controllers/sessions_controller.rb",
     "templates/app/helpers/application_helper.rb",
     "templates/app/models/mailer.rb",
     "templates/app/models/member.rb",
     "templates/app/models/member/authentication.rb",
     "templates/app/views/layouts/_application_javascript_includes.html.erb",
     "templates/app/views/layouts/_head.html.erb",
     "templates/app/views/layouts/application.html.erb",
     "templates/app/views/mailer/reset_password_message.erb",
     "templates/app/views/members/edit.html.erb",
     "templates/app/views/members/new.html.erb",
     "templates/app/views/members/show.html.erb",
     "templates/app/views/passwords/edit.html.erb",
     "templates/app/views/passwords/new.html.erb",
     "templates/app/views/passwords/reset.html.erb",
     "templates/app/views/passwords/sent.html.erb",
     "templates/app/views/sessions/_form.html.erb",
     "templates/app/views/sessions/_status.html.erb",
     "templates/app/views/sessions/new.html.erb",
     "templates/config/database.yml",
     "templates/lib/active_record_ext.rb",
     "templates/lib/token.rb",
     "templates/public/403.html",
     "templates/public/javascripts/ready.js",
     "templates/public/stylesheets/default.css",
     "templates/public/stylesheets/reset.css",
     "templates/test/ext/authentication.rb",
     "templates/test/ext/file_fixtures.rb",
     "templates/test/ext/time.rb",
     "templates/test/fixtures/members.yml",
     "templates/test/functional/application_controller_test.rb",
     "templates/test/functional/members_controller_test.rb",
     "templates/test/functional/passwords_controller_test.rb",
     "templates/test/functional/sessions_controller_test.rb",
     "templates/test/lib/active_record_ext_test.rb",
     "templates/test/lib/token_test.rb",
     "templates/test/test_helper.rb",
     "templates/test/unit/helpers/application_helper_test.rb",
     "templates/test/unit/mailer_test.rb",
     "templates/test/unit/member/authentication_test.rb",
     "templates/test/unit/member_test.rb"
  ]
  s.homepage = %q{http://github.com/Fingertips/rails-template}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["bin"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A self contained version of the Fingertips Rails template}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
