development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: test_app_development
  pool: 5
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: test_app_test
  pool: 5
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: test_app_production
  pool: 5